# Generated by Django 5.2.7 on 2025-11-08 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='due_data',
            new_name='due_date',
        ),
    ]
